package HistoryApp;


/**
* HistoryApp/HistoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from history.idl
* samedi 18 décembre 2021 20 h 22 WAT
*/

public abstract class HistoryPOA extends org.omg.PortableServer.Servant
 implements HistoryApp.HistoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addCalculHistory", new java.lang.Integer (0));
    _methods.put ("getCalculHistory", new java.lang.Integer (1));
    _methods.put ("deleteCalculHistory", new java.lang.Integer (2));
    _methods.put ("addConvertHistory", new java.lang.Integer (3));
    _methods.put ("getConvertHistory", new java.lang.Integer (4));
    _methods.put ("deleteConvertHistory", new java.lang.Integer (5));
    _methods.put ("shutdown", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HistoryApp/History/addCalculHistory
       {
         String cal = in.read_string ();
         this.addCalculHistory (cal);
         out = $rh.createReply();
         break;
       }

       case 1:  // HistoryApp/History/getCalculHistory
       {
         String $result[] = null;
         $result = this.getCalculHistory ();
         out = $rh.createReply();
         HistoryApp.HistoryPackage.listHelper.write (out, $result);
         break;
       }

       case 2:  // HistoryApp/History/deleteCalculHistory
       {
         this.deleteCalculHistory ();
         out = $rh.createReply();
         break;
       }

       case 3:  // HistoryApp/History/addConvertHistory
       {
         String cal = in.read_string ();
         this.addConvertHistory (cal);
         out = $rh.createReply();
         break;
       }

       case 4:  // HistoryApp/History/getConvertHistory
       {
         String $result[] = null;
         $result = this.getConvertHistory ();
         out = $rh.createReply();
         HistoryApp.HistoryPackage.listHelper.write (out, $result);
         break;
       }

       case 5:  // HistoryApp/History/deleteConvertHistory
       {
         this.deleteConvertHistory ();
         out = $rh.createReply();
         break;
       }

       case 6:  // HistoryApp/History/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HistoryApp/History:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public History _this() 
  {
    return HistoryHelper.narrow(
    super._this_object());
  }

  public History _this(org.omg.CORBA.ORB orb) 
  {
    return HistoryHelper.narrow(
    super._this_object(orb));
  }


} // class HistoryPOA
