package HistoryApp;


/**
* HistoryApp/History.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from history.idl
* samedi 18 décembre 2021 20 h 22 WAT
*/

public interface History extends HistoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface History
