package ConvertApp;


/**
* ConvertApp/Convert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from convert.idl
* samedi 18 décembre 2021 07 h 00 WAT
*/

public interface Convert extends ConvertOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Convert
