package ConvertApp;


/**
* ConvertApp/ConvertOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from convert.idl
* samedi 18 décembre 2021 07 h 00 WAT
*/

public interface ConvertOperations 
{
  String decimalToBinary (int decimal);
  String decimalToOctal (int decimal);
  String decimalToHexadecimal (int decimal);
  String BinaryToDecimal (String binary);
  String binaryToOctal (String binary);
  String binaryToHexadecimal (String binary);
  String octalToBinary (int octal);
  String octalToDecimal (int octal);
  String octalToHexaDecimal (int octal);
  String hexadecimalToBinary (String hexadecimal);
  String hexadecimalToOctal (String hexadecimal);
  String hexadecimalToDecimal (String hexadecimal);
  void shutdown ();
} // interface ConvertOperations
