package ConvertApp;

/**
* ConvertApp/ConvertHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from convert.idl
* samedi 18 décembre 2021 07 h 00 WAT
*/

public final class ConvertHolder implements org.omg.CORBA.portable.Streamable
{
  public ConvertApp.Convert value = null;

  public ConvertHolder ()
  {
  }

  public ConvertHolder (ConvertApp.Convert initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConvertApp.ConvertHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConvertApp.ConvertHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConvertApp.ConvertHelper.type ();
  }

}
