package CalculApp;


/**
* CalculApp/Calcul.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* vendredi 17 décembre 2021 19 h 13 WAT
*/

public interface Calcul extends CalculOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calcul
