package CalculApp;


/**
* CalculApp/CalculOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* vendredi 17 décembre 2021 19 h 13 WAT
*/

public interface CalculOperations 
{
  double addition (double a, double b);
  double soustraction (double a, double b);
  double multiplication (double a, double b);
  double division (double a, double b);
  void shutdown ();
} // interface CalculOperations
