package CalculApp;

/**
* CalculApp/CalculHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calcul.idl
* vendredi 17 décembre 2021 19 h 13 WAT
*/

public final class CalculHolder implements org.omg.CORBA.portable.Streamable
{
  public CalculApp.Calcul value = null;

  public CalculHolder ()
  {
  }

  public CalculHolder (CalculApp.Calcul initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CalculApp.CalculHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CalculApp.CalculHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CalculApp.CalculHelper.type ();
  }

}
